version: "3.4"

services:
  game-server:
    image: ${DEV_DOCKER_IMAGE}
    build:
      args:
        - BASE_DOCKER_IMAGE=${BASE_DOCKER_IMAGE}
      context: .
      dockerfile: php-dev.Dockerfile

    volumes:
      - .:/srv/game-worker


