version: "3.4"

services:
  game-server:
    image: ${DEV_DOCKER_IMAGE}
    build:
      args:
        - BASE_DOCKER_IMAGE=${BASE_DOCKER_IMAGE}
      context: docker/php/dev

    volumes:
      - .:/srv/game-worker

    ports:
      - "9001:9001"
      - "8080:8080"

  wamp-router:
    image: freeelephants/thruway:0.3.0
    volumes:
      - ./var/log/wamp:/var/log/thruway
    environment:
      - AUTHORIZATION_ENABLE=1
      - AUTH_METHOD=jwt
      - JWT_SECRET_KEY=foo
      - JWT_ALGOS=HS256
      - REALM=hexammon
      - ALLOW_REALM_AUTOCREATE=0
      - THRUWAY_DEBUG_ENABLE=1
